[package]
name = "memory-db"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = "0.4.39"
dashmap = "6.1.0"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.42.0", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
